/**
 * One-time script to geocode all suburb/town names from the CSV and output
 * a static JS lookup table for use in app.js.
 *
 * Respects Nominatim's 1 req/sec policy.
 * Usage: $env:NODE_OPTIONS="--use-system-ca"; web\node_modules\.bin\tsx.cmd supabase\geocode_suburbs.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { parse } from 'csv-parse/sync';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)); }

async function geocode(suburb: string): Promise<{ lat: number; lng: number } | null> {
  const url = `https://nominatim.openstreetmap.org/search?q=${encodeURIComponent(suburb + ', New Zealand')}&format=json&limit=1&countrycodes=nz`;
  try {
    const res = await fetch(url, { headers: { 'User-Agent': 'DentalCompareNZ/1.0' } });
    const data = await res.json() as Array<{ lat: string; lon: string }>;
    if (data.length > 0) {
      return { lat: parseFloat(parseFloat(data[0].lat).toFixed(5)), lng: parseFloat(parseFloat(data[0].lon).toFixed(5)) };
    }
  } catch (e) {
    console.error(`  Error geocoding "${suburb}":`, e);
  }
  return null;
}

async function main() {
  const csvPath = path.join(__dirname, '..', 'dental_clinics_all.csv');
  const raw = fs.readFileSync(csvPath, 'utf-8');
  const records = parse(raw, { columns: true, skip_empty_lines: true }) as Record<string, string>[];

  const suburbs = new Set<string>();
  for (const row of records) {
    const suburb = (row['suburb_town'] ?? '').trim();
    if (suburb) suburbs.add(suburb);
  }

  const sorted = [...suburbs].sort();
  console.log(`Geocoding ${sorted.length} unique suburbs (1/sec)…`);

  const results: Record<string, { lat: number; lng: number }> = {};
  const failed: string[] = [];

  for (let i = 0; i < sorted.length; i++) {
    const suburb = sorted[i];
    process.stdout.write(`[${i + 1}/${sorted.length}] ${suburb}… `);
    const coord = await geocode(suburb);
    if (coord) {
      results[suburb] = coord;
      console.log(`${coord.lat}, ${coord.lng}`);
    } else {
      failed.push(suburb);
      console.log('NOT FOUND');
    }
    if (i < sorted.length - 1) await sleep(1100);
  }

  // Write JS lookup table
  const lines2 = Object.entries(results)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => `  ${JSON.stringify(k)}: [${v.lat}, ${v.lng}]`);

  const output = `// Auto-generated by geocode_suburbs.ts — do not edit manually
const SUBURB_COORDS = {
${lines2.join(',\n')}
};
`;

  const outPath = path.join(__dirname, '..', 'docs', 'assets', 'js', 'suburb_coords.js');
  fs.writeFileSync(outPath, output, 'utf-8');
  console.log(`\nWritten to ${outPath}`);
  console.log(`Geocoded: ${Object.keys(results).length}, Failed: ${failed.length}`);
  if (failed.length) console.log('Failed:', failed.join(', '));
}

main();
